carcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cars/', views.cars_index, name='index'),
    path('cars/<int:car_id>/', views.cars_detail, name='detail'),
    path('cars/create/', views.CarCreate.as_view(), name='cars_create'),
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='cars_update'),
    path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='cars_delete'),
    path('cats/<int:car_id>/add_fueling/', views.add_fueling, name='add_fueling'),
    path('paint/', views.PaintList.as_view(), name='paint_index'),
    path('paint/<int:pk>/', views.PaintDetail.as_view(), name='paint_detail'),
    path('paint/create/', views.PaintCreate.as_view(), name='paint_create'),
    path('paint/<int:pk>/update/', views.PaintUpdate.as_view(), name='paint_update'),
    path('paint/<int:pk>/delete/', views.PaintDelete.as_view(), name='paint_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

FUEL = (
    ('R', 'Regular'),
    ('M', 'Midgrade'),
    ('P', 'Premium')
)

# Create your models here.

class Paint(models.Model):
  color = models.CharField(max_length=50)
  finish = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('paint_detail', kwargs={'pk': self.id})

class Car(models.Model):
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    year = models.IntegerField()
    paint = models.ManyToManyField(Paint)

    def __str__(self):
        return self.make + ' ' + self.model

    def get_absolute_url(self):
        return reverse('detail', kwargs={'car_id': self.id})

class Fueling(models.Model):
    date = models.DateField('fueling date')
    fuel = models.CharField(
      max_length=1, 
      choices=FUEL,
      default=FUEL[0][0])

    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_fuel_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Fueling

class FuelingForm(ModelForm):
  class Meta:
    model = Fueling
    fields = ['date', 'fuel']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from .models import Car, Paint
from .forms import FuelingForm

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def cars_index(request):
  return render(request, 'cars/index.html', { 'cars': cars })

def cars_index(request):
  cars = Car.objects.all()
  return render(request, 'cars/index.html', { 'cars': cars })

def cars_detail(request, car_id):
  car = Car.objects.get(id=car_id)
  fueling_form = FuelingForm()
  return render(request, 'cars/detail.html', { 'car': car, 'fueling_form': fueling_form })

class CarCreate(CreateView):
  model = Car
  fields = '__all__'
  success_url = '/cars/'

class CarUpdate(UpdateView):
  model = Car
  fields = '__all__'

class CarDelete(DeleteView):
  model = Car
  success_url = '/cars/'

def add_fueling(request, car_id):
  form = FuelingForm(request.POST)
  if form.is_valid():
    new_fuel = form.save(commit=False)
    new_fuel.car_id = car_id
    new_fuel.save()
  return redirect('detail', car_id=car_id)

def assoc_paint(request, car_id, paint_id):
  Car.objects.get(id=car_id).paint.add(paint_id)
  return redirect('detail', car_id=car_id)

def unassoc_paint(request, car_id, paint_id):
  Car.objects.get(id=car_id).paint.remove(paint_id)
  return redirect('detail', car_id=car_id)

class PaintList(ListView):
  model = Paint

class PaintDetail(DetailView):
  model = Paint

class PaintCreate(CreateView):
  model = Paint
  fields = '__all__'

class PaintUpdate(UpdateView):
  model = Paint
  fields = ['color', 'finish']

class PaintDelete(DeleteView):
  model = Paint
  success_url = '/paint/'

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>About the Car Collector</h1>
<hr />
<p>Hire the Car Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Car Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;CarCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'paint_create' %}">Add Paint</a></li>
            <li><a href="{% url 'paint_index' %}">View All Paint</a></li>
            <li><a href="{% url 'cars_create' %}">Add a Car</a></li>
            <li><a href="{% url 'index' %}">View All My Cars</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2021 Car Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Car Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ car.make }} {{ car.model }}</span>
        <p>Description: {{ car.description }}</p>
        <p>Year: {{ car.year }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cars_update' car.id %}">Edit</a>
        <a href="{% url 'cars_delete' car.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_fueling' car.id %}" method="post">
      {% csrf_token %} {{ fueling_form.as_p }}
      <input type="submit" class="btn" value="Add Fuel" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Fuel</th>
        </tr>
      </thead>
      <tbody>
        {% for fueling in car.fueling_set.all %}
        <tr>
          <td>{{fueling.date}}</td>
          <td>{{fueling.get_fuel_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ car.make }} {{ car.model }}'s Paint</h3>
    {% if car.paint.count %} {% for paint in car.paint.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span>{{ paint.color }}</span> {{ paint.finish }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'unassoc_paint' car.id paint.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Paint :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Paint</h3>
    {% if paint.count %} {% for paint in paint.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <span>{{ paint.color }}</span> {{ paint.finish }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_paint' car.id paint.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{car.make}} {{ car.model }} Already Has All Paint Available</h5>
    {% endif %}
  </div>
</div>

<script>
  var dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });
  var selectEl = document.getElementById("id_fuel");
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Car List</h1>

{% for car in cars %}
<div class="card">
    <a href="{% url 'detail' car.id %}">
    <div class="card-content">
      <span class="card-title">{{ car.make }} {{ car.model}}</span>
      <p>Description: {{ car.description }}</p>
      <p>Age: {{ car.year }}</p>
    </div>
</a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.make }} {{ object.model }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' car.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.make}} {{object.model}}</span></h1>
  {% else %}
    <h1>Add Car</h1>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/paint_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Paint</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'paint_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/paint_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Paint Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ paint.color }}</span>
        <p>Finish: {{ paint.finish }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'paint_update' paint.id %}">Edit</a>
        <a href="{% url 'paint_delete' paint.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/paint_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Paint</h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/paint_list.html
{% extends 'base.html' %} {% block content %}

<h1>Paint List</h1>

{% for paint in paint_list %}
<a href="{% url 'paint_detail' paint.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ paint.color }}</span>
      <p>Finish: {{ paint.finish }}</p>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}